## Продукт (Товар)

Products_Model_Product:
  tableName: products_product_must_deleted
  actAs:
    Timestampable:
  options:
    type: INNODB
    collate: utf8_unicode_ci
    charset: utf8
  columns:
    id:
      type: integer(4)
      unsigned: true
      primary: true
      autoincrement: true
    image_filename:
      type: string(45)
      notnull: true
    name: string(255)
    description: string()
    visible:
      type: boolean
      notnull: true
      default: true