<div class="innerSearchBlock">
    <div class="WideListOtziv WideListOtziv2">
        <a class="feedback" href="<?php echo $this->url(array(
                                        'module' => 'catalog',
                                        'controller' => 'reviews',
                                        'action' => 'new',
                                        'id' => $this->product->id),
                                    'default', true); ?>"><?php echo $this->translate('Написать отзыв'); ?></a>
        <?php $count = $this->reviewsCount($this->product->id);  ?>
        <?php if ($count > 0): ?>
        <h3><?php echo $this->translate('Отзывы'); ?><span> (<?php echo $count; ?>)</span></h3>
            <?php foreach ($this->reviews as $review):?>
            <div class="otzivDescr">
                <div class="termOfUse"><?php echo $this->translate('Опыт использования'); ?>:
                    <span><?php echo $review->mark_formated; ?></span></div>
                <div class="userName">
                    <a href="<?php echo $this->url(array(
                                                    'module' => 'users',
                                                    'controller' => 'index',
                                                    'action' => 'profile',
                                                    'id' => $review->User->id),
                                                'default', true); ?>">
                        <?php echo $review->User->login; ?>
                    </a> <?php echo $review->created_at_formated; ?>
                </div>
                <dl>
                    <?php if (strlen($review->advantages)): ?>
                        <dt><?php echo $this->translate('Достоинства'); ?>:</dt> <dd><?php echo $review->advantages; ?></dd>
                    <?php endif; ?>
                    <?php if (strlen($review->disadvantages)): ?>
                        <dt><?php echo $this->translate('Недостатки'); ?>:</dt> <dd><?php echo $review->disadvantages; ?></dd>
                    <?php endif; ?>
                    <?php if (strlen($review->comment)): ?>
                        <dt><?php echo $this->translate('Комментарий'); ?>:</dt> <dd><?php echo $review->comment; ?></dd>
                    <?php endif; ?>
                </dl>
            </div>
            <?php endforeach;?>
            <h6><a href="<?php echo $this->url(array(
                                        'module' => 'catalog',
                                        'controller' => 'reviews',
                                        'action' => 'list',
                                        'id' => $this->productId),
                                    'default', true); ?>"><?php echo $this->translate('Все отзывы'); ?></a> <span>(<?php echo $count; ?>)</span></h6>
        <?php else:?>
            <h3 class="wideListOtzivNo"><?php echo $this->translate('Отзывов нет'); ?></h3>
        <?php endif;?>
    </div>
    <div class="innderSearchBlockBot"></div>
</div>