<?php

/**
 * Features_Model_Base_Group
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property Doctrine_Collection $Categories
 * @property Doctrine_Collection $Sets
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Features_Model_Base_Group extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('features_groups');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Catalog_Model_Category as Categories', array(
             'local' => 'id',
             'foreign' => 'features_group_id'));

        $this->hasMany('Features_Model_Set as Sets', array(
             'local' => 'id',
             'foreign' => 'features_group_id'));
    }
}