<?php

/**
 * Catalog_Model_Review
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Catalog_Model_Review extends Catalog_Model_Base_Review
{
    public function getCreatedAtFormated(){
        $date = new Zend_Date($this->created_at);
        return $date->toString('dd.MM.Y');
    }

    public function getMarkFormated(){
        $view = Zend_Layout::getMvcInstance()->getView();
        if ($this->mark > 12) {
            return $view->translate('больше 1 года');
        } elseif ($this->mark == 12) {
            return $view->translate('1 год');
        } else {
            return $this->mark . ' ' . $view->translate(array(_('месяц'), _('месяца'), _('месяцев'), $this->mark, Zend_Locale::findLocale()));
        }
    }
}