<?php

/**
 * Advertisment_Model_Base_Banner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property enum $type
 * @property string $background_color
 * @property string $background_image
 * @property string $url
 * @property enum $show_on
 * @property string $page_placement
 * @property boolean $rotation
 * @property timestamp $last_renewal_date
 * @property timestamp $untill_date
 * @property enum $status
 * @property int $period
 * @property int $impressions
 * @property Doctrine_Collection $Images
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Advertisment_Model_Base_Banner extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('advertisment_banners');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'notnull' => true,
             'values' => 
             array(
              0 => 'top',
              1 => 'right',
             ),
             ));
        $this->hasColumn('background_color', 'string', 7, array(
             'type' => 'string',
             'length' => '7',
             ));
        $this->hasColumn('background_image', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('show_on', 'enum', null, array(
             'type' => 'enum',
             'notnull' => true,
             'values' => 
             array(
              0 => 'anywhere',
              1 => 'on-main',
              2 => 'none',
              3 => 'in-place',
             ),
             'default' => 'none',
             ));
        $this->hasColumn('page_placement', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('rotation', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('last_renewal_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('untill_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'notnull' => true,
             'values' => 
             array(
              0 => 'available',
              1 => 'disable',
             ),
             'default' => 'disable',
             ));
        $this->hasColumn('period', 'int', 4, array(
             'type' => 'int',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('impressions', 'int', 4, array(
             'type' => 'int',
             'notnull' => true,
             'length' => '4',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Advertisment_Model_BannerImage as Images', array(
             'local' => 'id',
             'foreign' => 'banner_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}