## Категория - Продукт
## Связь "many to many"

Catalog_Model_CategoryProduct:
  tableName: catalog_categories_products
  options:
    type: INNODB
    collate: utf8_unicode_ci
    charset: utf8
  columns:
    id:
      type: integer(4)
      unsigned: true
      primary: true
      autoincrement: true
    product_id:
      type: integer(4)
      unsigned: true
    category_id:
      type: integer(4)
      unsigned: true
  relations:
    Product:
      class: Catalog_Model_Product
      local: product_id
      foreign: id
      foreignAlias: CategoryProduct
      onUpdate: CASCADE
      onDelete: CASCADE
    Category:
      class: Catalog_Model_Category
      local: category_id
      foreign: id
      foreignAlias: CategoryProduct
      onUpdate: CASCADE
      onDelete: CASCADE