<?php $keywords = array('Apple iPhone', 'Acer Aspire One', 'Nokia N97', 'Nikon D70' ); ?>
<?php $keyword = $keywords[mt_rand(0, 3)]; ?>
<div class="headerSearch">
    <form  id="<?php echo $this->element->getId();?>"
       action="<?php echo $this->element->getAction();?>"
       method="<?php echo $this->element->getMethod();?>">
        <div class="headerSearchForInp">
            <?php echo $this->element->keywords;?>
            <?php echo $this->element->city;?>
            <!--hidden block-->
            <ul id="headerSearchHint">
                <li>Sony DSLR 500 <span><i>1</i> результат</span></li>
                <li>Sony DSLR 700 <span><i>23</i> результатов</span></li>
                <li>Sony DSLK 10 <span><i>8</i> результатов</span></li>
                <li>Sony DSLR 500 <span><i>1</i> результат</span></li>
                <li>Sony DSLR 700 <span><i>23</i> результатов</span></li>
            </ul>
            <!--/hidden block-->
            <?php echo $this->element->submit;?>
            <div id="headerSearchChooseCity"><i><span><?php echo $this->element->city->getValue(); ?></span></i>
                <!--hidden block-->
                <ul>
                    <?php foreach ($this->GetCities() as $city):?>
                    <li><b><?php echo $city; ?></b></li>
                    <?php endforeach;?>
                </ul>
                <!--/hidden block-->
            </div>
        </div>
    </form>
    <div id="headerSearchExample">Например: <span><?php echo $keyword; ?></span></div>
    <div class="headerSearchLeft"></div>
    <div class="headerSearchRight"></div>
</div>