<?php

/**
 * Advertisment_Model_BannerImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Advertisment_Model_BannerImage extends Advertisment_Model_Base_BannerImage
{
    /**
     * Путь к изображению относительно public
     */
    const PUBLIC_UPLOAD_PATH = '/upload/images/banners';

    /**
     * Возвращает абсолютный путь к папке с оригинальными изображениями
     *
     * @return string
     */
    public static function getImageAbsoluteUploadPath()
    {
        return realpath(APPLICATION_PATH . '/../public' . self::PUBLIC_UPLOAD_PATH);
    }

    /**
     * Return url path to the image file
     *
     * @return string
     */
    public function getImageUrl()
    {
        if (strlen($this->image_filename)) {
            return self::PUBLIC_UPLOAD_PATH
                . '/'
                . $this->image_filename;
        }
        return NULL;
    }
}