<ul>
    <li><a href="#0-9">0-9</a></li>
    <?php foreach (range('A','Z') as $char): ?>
        <?php if(array_key_exists($char, $this->alpabetData)): ?>
            <li><a href="#<?php echo $char ?>"><?php echo $char ?></a></li>
        <?php else: ?>
            <li><?php echo $char ?></li>
        <?php endif; ?>
    <?php endforeach; ?>
</ul>
<ul>
    <?php $alpabet = array('А', 'Б', 'В', 'Г', 'Д', 'Е', 'Ж', 'З', 'И', 'К', 'Л', 'М', 'Н', 'О', 'П', 'Р', 'С', 'Т', 'У', 'Ф', 'Х', 'Ц', 'Ч','Ш', 'Щ', 'Э', 'Ю', 'Я') ?>
    <?php foreach ($alpabet as $char): ?>
        <?php if(array_key_exists($char, $this->alpabetData)): ?>
            <li><a href="#<?php echo $char; ?>"><?php echo $char ?></a></li>
        <?php else: ?>
            <li><?php echo $char ?></li>
        <?php endif; ?>
    <?php endforeach; ?>
</ul>