<?php

/**
 * Shops_Model_Base_Comment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property enum $mark
 * @property Shops_Model_Shop $CommentedShop
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Shops_Model_Base_Comment extends Comments_Model_Comment
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('shops_comments');
        $this->hasColumn('mark', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'good',
              1 => 'normal',
              2 => 'bad',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Shops_Model_Shop as CommentedShop', array(
             'local' => 'entity_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($softdelete0);
    }
}