<h2><?php echo $this->title; ?></h2>

<div class="action">
    <a href="<?php echo $this->url(array(
            'module' => 'users',
            'controller' => 'index',
            'action' => 'create-user'),
        'default', true); ?>"><?php echo $this->translate('Новый пользователь'); ?></a>
</div>
<br />

<?php if (is_object($this->users) && $this->users->count()): ?>
    <table id="tableUsersList" class="table-list">
        <thead>
            <tr>
                <th><?php echo $this->translate('Email'); ?></th>
                <th><?php echo $this->translate('Имя'); ?></th>
                <th><?php echo $this->translate('Роль'); ?></th>
                <th><?php echo $this->translate('Зарегистрирован'); ?></th>
                <th><?php echo $this->translate('Действие'); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->users as $user) : ?>
                <tr>
                    <td>
                        <?php echo $user->email; ?>
                    </td>
                    <td>
                        <?php echo $user->name; ?>
                    </td>
                    <td>
                        <?php echo $user->localized_role; ?>
                    </td>
                    <td>
                        <?php echo $user->created_at; ?>
                    </td>
                    <td class="action">
                        <a href="<?php echo $this->url(array(
                            'module'=>'users',
                            'action'=>'edit',
                            'id'=>$user->id,
                        ), 'default', true); ?>"><?php echo $this->translate('Редактировать'); ?></a>
                        <a href="<?php echo $this->url(array(
                            'module'=>'users',
                            'action'=>'delete',
                            'id'=>$user->id,
                        ), 'default', true); ?>"><?php echo $this->translate('Удалить'); ?></a>
                        <?php if($user->role == Users_Model_User::ROLE_MERCHANT): ?>
                            | <a href="<?php echo $this->url(array(
                                'module' => 'shops',
                                'controller' =>'index',
                                'action' => 'new',
                                'id' => $user->id
                            ), 'default', true); ?>"><?php echo $this->translate('Добавить магазин'); ?></a>
                            <a href="<?php echo $this->url(array(
                                'module' => 'shops',
                                'controller' =>'index',
                                'action' => 'list-admin',
                                'id' => $user->id
                            ), 'default', true); ?>"><?php echo $this->translate('Список'); ?></a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<br />

<div class="pager">
    <?php echo $this->pagination($this->paginator)->create_links('admin'); ?>
</div>

<?php else: ?>
    <?php echo $this->translate('Пока еще нет пользователей.'); ?>
<?php endif; ?>
