<?php

/**
 * Marketplace_Model_Base_Category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $Products
 * @property Doctrine_Collection $CategoryProduct
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Marketplace_Model_Base_Category extends Categories_Model_Category
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('marketplace_categories');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Marketplace_Model_Product as Products', array(
             'refClass' => 'Marketplace_Model_CategoryProduct',
             'local' => 'category_id',
             'foreign' => 'product_id'));

        $this->hasMany('Marketplace_Model_CategoryProduct as CategoryProduct', array(
             'local' => 'id',
             'foreign' => 'category_id'));
    }
}