## картики баннеров

Advertisment_Model_BannerImage:
  tableName: advertisment_banners_images
  options:
    type: INNODB
    collate: utf8_unicode_ci
    charset: utf8
  columns:
    id:
      type: integer(4)
      unsigned: true
      primary: true
      autoincrement: true
    banner_id:
      type: integer(4)
      unsigned: true
    image_filename:
      type: string(45)
      notnull: true
  relations:
    Banner:
      class: Advertisment_Model_Banner
      local: banner_id
      foreign: id
      foreignAlias: Images
      onUpdate: CASCADE
      onDelete: CASCADE