<form id="<?php echo $this->element->getId();?>"
      action="<?php echo $this->element->getAction();?>"
          method="<?php echo $this->element->getMethod();?>" class="registerCompanyP">
    <div class="leftColumnReg">

        <div class="registerRows bot33">
            <div class="labelContenter">
                <label for="<?php echo $this->element->login->getName(); ?>"><?php echo $this->translate('Логин'); ?>:</label>
            </div>
            <div class="inputTextWide inputTextMiddle"><?php echo $this->element->login; ?></div>
            <?php echo $this->renderElementErrors($this->element->login); ?>
        </div>

        <div class="registerRows bot18">
            <?php echo $this->element->captcha; ?>
            <?php echo $this->renderElementErrors($this->element->captcha); ?>
        </div>

    </div>
    <div class="formSbutton">
        <input type="submit" value="<?php echo $this->translate('Отправить'); ?>"/>

    </div>

</form>