<?php
/**
 * Default pagination style
 *
 * @preview  « 1 2 … 5 6 7 8 9 10 11 12 13 14 … 25 26 »
 *
 */
?>
<?php if ($this->total_pages > 1):?>
<div class="innerPageNav">
    <span><?php echo $this->translate('Страница'); ?>:</span>
        <ul>

        <?php if ($this->total_pages < 13): /* « Previous  1 2 3 4 5 6 7 8 9 10 11 12  Next » */ ?>

                <?php for ($i = 1; $i <= $this->total_pages; $i++): ?>
                        <?php if ($i == $this->current_page): ?>
                                <li class="adminPageNavActive"><?php echo $i ?></li>
                        <?php else: ?>
                                <li><a href="<?php echo $this->queryUrl(array('page' => $i)); ?>"><?php echo $i ?></a></li>
                        <?php endif ?>
                <?php endfor ?>

        <?php elseif ($this->current_page < 9): /* « Previous  1 2 3 4 5 6 7 8 9 10 … 25 26  Next » */ ?>

                <?php for ($i = 1; $i <= 10; $i++): ?>
                        <?php if ($i == $this->current_page): ?>
                                <li class="adminPageNavActive"><?php echo $i ?></li>
                        <?php else: ?>
                                <li><a href="<?php echo $this->queryUrl(array('page' => $i)); ?>"><?php echo $i ?></a></li>
                        <?php endif ?>
                <?php endfor ?>

                <li>&hellip;</li>
                <li><a href="<?php echo $this->queryUrl(array('page' => $this->total_pages - 1)); ?>"><?php echo $this->total_pages - 1 ?></a></li>
                <li><a href="<?php echo $this->queryUrl(array('page' =>  $this->total_pages )); ?>"><?php echo $this->total_pages ?></a></li>

        <?php elseif ($this->current_page > $this->total_pages - 8): /* « Previous  1 2 … 17 18 19 20 21 22 23 24 25 26  Next » */ ?>

                <li><a href="<?php echo $this->queryUrl(array('page' => 1)); ?>">1</a></li>
                <li><a href="<?php echo $this->queryUrl(array('page' => 2)); ?>">2</a></li>
                <li>&hellip;</li>

                <?php for ($i = $this->total_pages - 9; $i <= $this->total_pages; $i++): ?>
                        <?php if ($i == $this->current_page): ?>
                                <li class="adminPageNavActive"><?php echo $i ?></li>
                        <?php else: ?>
                                <li><a href="<?php echo $this->queryUrl(array('page' => $i)); ?>"><?php echo $i ?></a></li>
                        <?php endif ?>
                <?php endfor ?>

        <?php else: /* « Previous  1 2 … 5 6 7 8 9 10 11 12 13 14 … 25 26  Next » */ ?>

                <li><a href="<?php echo $this->queryUrl(array('page' => 1)); ?>">1</a></li>
                <li><a href="<?php echo $this->queryUrl(array('page' => 2)); ?>">2</a></li>
                <li>&hellip;</li>

                <?php for ($i = $this->current_page - 5; $i <= $this->current_page + 5; $i++): ?>
                        <?php if ($i == $this->current_page): ?>
                                <li class="adminPageNavActive"><?php echo $i ?></li>
                        <?php else: ?>
                                <li><a href="<?php echo $this->queryUrl(array('page' => $i)); ?>"><?php echo $i ?></a></li>
                        <?php endif ?>
                <?php endfor ?>

                <li>&hellip;</li>
                <li><a href="<?php echo $this->queryUrl(array('page' => $this->total_pages - 1)); ?>"><?php echo $this->total_pages - 1 ?></a></li>
                <li><a href="<?php echo $this->queryUrl(array('page' => $this->total_pages )); ?>"><?php echo $this->total_pages ?></a></li>

        <?php endif ?>

    </ul>
    <div>
        <?php if ($this->previous_page): ?>
                <a href="<?php echo $this->queryUrl(array('page' => $this->previous_page)); ?>" class="innerPageNavPrev"><?php echo $this->translate('предыдущая'); ?></a>
        <?php else: ?>
                <a class="innerPageNavPrev notactiv"><?php echo $this->translate('предыдущая'); ?></a>
        <?php endif ?>

        <?php if ($this->next_page): ?>
                <a href="<?php echo $this->queryUrl(array('page' => $this->next_page)); ?>" class="innerPageNavNext"><?php echo $this->translate('следующая'); ?></a>
        <?php else: ?>
                <a class="innerPageNavNext notactiv"><?php echo $this->translate('следующая'); ?></a>
        <?php endif ?>
    </div>
</div>
<?php endif ?>