<?php

/**
 * Comments_Model_Comment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Comments_Model_Comment extends Comments_Model_Base_Comment implements Zend_Acl_Resource_Interface
{

     /**
     * Return user resource id
     *
     * @return string
     */
    public function getResourceId()
    {
        if ($this->user_id == @Zend_Auth::getInstance()->getIdentity()->id) {
            return 'object:comments:comment:my';
        } else {
            return 'object:comments:comment:foreign';
        }
    }
}