<?php

/**
 * Catalog_Model_Base_Product
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int $clicks
 * @property integer $brand_id
 * @property decimal $min_price
 * @property decimal $max_price
 * @property decimal $avg_price
 * @property string $image_to_download
 * @property Catalog_Model_Brand $Brand
 * @property Doctrine_Collection $Categories
 * @property Doctrine_Collection $Images
 * @property Doctrine_Collection $ProductsList
 * @property Doctrine_Collection $Prices
 * @property Doctrine_Collection $CategoryProduct
 * @property Doctrine_Collection $FeatureProduct
 * @property Doctrine_Collection $Reviews
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Catalog_Model_Base_Product extends Products_Model_Product
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('catalog_products');
        $this->hasColumn('clicks', 'int', 4, array(
             'type' => 'int',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('brand_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('min_price', 'decimal', 14, array(
             'type' => 'decimal',
             'length' => '14',
             'scale' => '2',
             ));
        $this->hasColumn('max_price', 'decimal', 14, array(
             'type' => 'decimal',
             'length' => '14',
             'scale' => '2',
             ));
        $this->hasColumn('avg_price', 'decimal', 14, array(
             'type' => 'decimal',
             'length' => '14',
             'scale' => '2',
             ));
        $this->hasColumn('image_to_download', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Catalog_Model_Brand as Brand', array(
             'local' => 'brand_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('Catalog_Model_Category as Categories', array(
             'refClass' => 'Catalog_Model_CategoryProduct',
             'local' => 'product_id',
             'foreign' => 'category_id'));

        $this->hasMany('Catalog_Model_ProductImage as Images', array(
             'local' => 'id',
             'foreign' => 'product_id'));

        $this->hasMany('Catalog_Model_MyProductsList as ProductsList', array(
             'local' => 'id',
             'foreign' => 'product_id'));

        $this->hasMany('Catalog_Model_Price as Prices', array(
             'local' => 'id',
             'foreign' => 'product_id'));

        $this->hasMany('Catalog_Model_CategoryProduct as CategoryProduct', array(
             'local' => 'id',
             'foreign' => 'product_id'));

        $this->hasMany('Catalog_Model_FeatureProduct as FeatureProduct', array(
             'local' => 'id',
             'foreign' => 'product_id'));

        $this->hasMany('Catalog_Model_Review as Reviews', array(
             'local' => 'id',
             'foreign' => 'product_id'));
    }
}