<?php

/**
 * Catalog_Model_Base_Review
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $advantages
 * @property string $disadvantages
 * @property integer $approve
 * @property integer $product_id
 * @property integer $user_id
 * @property Catalog_Model_Product $Product
 * @property Users_Model_User $User
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Catalog_Model_Base_Review extends Reviews_Model_Review
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('catalog_products_reviews');
        $this->hasColumn('advantages', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('disadvantages', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('approve', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '1',
             ));
        $this->hasColumn('product_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Catalog_Model_Product as Product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Users_Model_User as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}