<?php echo $this->doctype('XHTML11') . "\n"; ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php echo $this->headTitle('EPRICE.KZ') . "\n"; ?>
        <?php echo $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8') . "\n"; ?>
        <?php echo $this->headLink()->appendStylesheet('/stylesheets/admin.css')
                                    ->appendStylesheet('/stylesheets/admin-ie6.css', 'screen', 'IE 6')
                                    ->appendStylesheet('/stylesheets/admin-firm.css')
                                    ->appendStylesheet('/stylesheets/admin-goods.css')
                                    ->appendStylesheet('/stylesheets/admin-harak-shabl.css') // !!!
                                    ->appendStylesheet('/stylesheets/admin-harak.css') // !!!
                                    ->appendStylesheet('/stylesheets/common.css')
                                    ->appendStylesheet('/stylesheets/admin-pad.css') . "\n"; ?>
        <?php echo $this->headScript()->prependFile('http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js')
                                      ->appendFile('/javascripts/jsScroll.js')
                                      ->appendFile('/javascripts/jquery.client-upload.js')
                                      ->appendFile('/javascripts/jquery.client.admin.js')
                                      ->appendFile('/javascripts/jquery.client.js') . "\n"; ?>
    </head>
    <body>

        <!--main-->
        <div class="main">
            <div class="adminHeader">
                <a href="<?php echo $this->url(array(
                        'module' => 'default',
                        'controller' => 'index',
                        'action' => 'admin'),
                    'default', true); ?>" class="adminLogo">eprice.kz</a>
                <span class="adminLoginInfo"><a href="<?php echo $this->url(array(
                            'module' => 'users',
                            'controller' => 'index',
                            'action' => 'logout'),
                        'default', true); ?>"><?php echo $this->translate('Выйти'); ?></a><?php echo $this->translate('Вы вошли как'); ?> <b>admin</b></span>
                <h2><?php echo $this->translate('Административная часть сайта'); ?></h2>
            </div>
            <div class="adminContentWrap">
                <?php echo $this->adminMenu(); ?>

                <!--главный контент-->
                <div class="adminMainContenter">
                    <?php echo $this->flashMessenger(); ?>
                    <?php echo $this->layout()->content; ?>
                </div>
                <!--/главный контент-->
            </div>
        </div>

        <!--footer-->
        <div class="footerWrap">
            <div class="footer">
                <div class="footerCopy">
                    <ul>
                        <li><a href="http://eprice.kz/page/about">О проекте</a></li>
                        <li><a href="http://eprice.kz/page/contacts">Контакты</a></li>
                        <li><a href="http://eprice.kz/pages/index/sitemap">Карта сайта</a></li>
                    </ul>
			ТОО &laquo;price.kz&raquo; &copy; 2010
                </div>

                <ul class="footerBusinessLinks">
                    <li><a href="http://eprice.kz/pages/index/prices">Размещение прайсов</a></li>
                    <li><a href="http://eprice.kz/page/advertisment">Реклама на сайте</a></li>
                </ul>
               

            </div>
        </div>
        <!--/footer-->
    </body>
</html>
