<h1><?php echo $this->title; ?></h1>
<div class="adminSortByType">
    <a href="<?php echo $this->url(array(
                                'module'=>$this->moduleName,
                                'controller'=>$this->controllerName,
                                'action'=>'new-admin',
                                'visible'=>'-1'
                            ), 'default', true); ?>"
        <?php echo $this->visible == -1 ? 'class="adminSortByTypeActive"' : ''?>>
                            скрытые
    </a>
    <a href="<?php echo $this->url(array(
                                'module'=>$this->moduleName,
                                'controller'=>$this->controllerName,
                                'action'=>'new-admin'
                            ), 'default', true); ?>"
       <?php echo $this->visible == 0 ? 'class="adminSortByTypeActive"' : ''?>>
                            все
    </a>
    <span><?php echo $this->translate('показывать'); ?>:</span>
</div>
<?php if ($this->products): ?>
<?php echo $this->render('partial/item-in-row.phtml'); ?>
<?php else: ?>
<?php echo $this->translate('Новых товаров в данный момент нет'); ?>
<?php endif; ?>