<div class="baraholkaMyListItemWideTextWrap heightAuto">
    <form  id="<?php echo $this->element->getId();?>"
           action="<?php echo $this->element->getAction();?>"
           method="<?php echo $this->element->getMethod();?>">
        <div class="baraholkaMyListItemWideText blueBack"><?php echo $this->element->text;?></div>
        <?php echo $this->element->entity_id; ?>
        <?php echo $this->element->user_id; ?>
        <?php echo $this->element->parent_id; ?>
        <?php echo $this->element->submit; ?>
    </form>
</div>