<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addshopsmanagers extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('shops_managers', array(
             'id' => 
             array(
              'type' => 'integer',
              'unsigned' => true,
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'phone' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'email' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'unique' => true,
              'email' => true,
              'length' => 128,
             ),
             'city' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 140,
             ),
             'shop_id' => 
             array(
              'type' => 'integer',
              'unsigned' => true,
              'length' => 4,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('shops_managers');
    }
}