<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version15 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('catalog_products', 'visible', 'tinyint', '1', array(
             ));
        $this->addColumn('catalog_products', 'clicks', 'int', '4', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('catalog_products', 'visible');
        $this->removeColumn('catalog_products', 'clicks');
    }
}