<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version17 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('shops', 'status', 'enum', '', array(
             'notnull' => '1',
             'values' => 
             array(
              0 => 'available',
              1 => 'disable',
              2 => 'new',
             ),
             'default' => 'disable',
             ));
    }

    public function down()
    {

    }
}