<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version21 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('features_fields', 'slider', 'boolean', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('features_fields', 'slider');
    }
}