<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addshops extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('shops', array(
             'id' => 
             array(
              'type' => 'integer',
              'unsigned' => true,
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'city' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 140,
             ),
             'address' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'site' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'phone' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'email' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'unique' => true,
              'email' => true,
              'length' => 128,
             ),
             'image_filename' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 45,
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'unsigned' => true,
              'length' => 4,
             ),
             'work_time' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'credit' => 
             array(
              'type' => 'int',
              'length' => 1,
             ),
             'delivery' => 
             array(
              'type' => 'string',
              'length' => 120,
             ),
             'status' => 
             array(
              'type' => 'enum',
              'notnull' => true,
              'values' => 
              array(
              0 => 'available',
              1 => 'disable',
              ),
              'length' => NULL,
             ),
             'last_renewal_date' => 
             array(
              'type' => 'datetime',
              'length' => NULL,
             ),
             'untill_date' => 
             array(
              'type' => 'datetime',
              'length' => NULL,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('shops');
    }
}