<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version19 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('features_fields', 'unit', 'string', '140', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('features_fields', 'unit');
    }
}