<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addfks extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('catalog_categories_products', 'catalog_categories_products_product_id_catalog_products_id', array(
             'name' => 'catalog_categories_products_product_id_catalog_products_id',
             'local' => 'product_id',
             'foreign' => 'id',
             'foreignTable' => 'catalog_products',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('catalog_categories_products', 'catalog_categories_products_category_id_catalog_categories_id', array(
             'name' => 'catalog_categories_products_category_id_catalog_categories_id',
             'local' => 'category_id',
             'foreign' => 'id',
             'foreignTable' => 'catalog_categories',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('shops_managers', 'shops_managers_shop_id_shops_id', array(
             'name' => 'shops_managers_shop_id_shops_id',
             'local' => 'shop_id',
             'foreign' => 'id',
             'foreignTable' => 'shops',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('shops', 'shops_user_id_users_id', array(
             'name' => 'shops_user_id_users_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'users',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
    }

    public function down()
    {
        $this->dropForeignKey('catalog_categories_products', 'catalog_categories_products_product_id_catalog_products_id');
        $this->dropForeignKey('catalog_categories_products', 'catalog_categories_products_category_id_catalog_categories_id');
        $this->dropForeignKey('shops_managers', 'shops_managers_shop_id_shops_id');
        $this->dropForeignKey('shops', 'shops_user_id_users_id');
    }
}