<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version20 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('features_fields', 'features_fields_unit', array(
             'fields' => 
             array(
              'unit' => 
              array(
              'length' => '10',
              ),
             ),
             ));
    }

    public function down()
    {
        $this->removeIndex('features_fields', 'features_fields_unit', array(
             'fields' => 
             array(
              'unit' => 
              array(
              'length' => '10',
              ),
             ),
             ));
    }
}