<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addusers extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('users', array(
             'id' => 
             array(
              'type' => 'integer',
              'unsigned' => true,
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'email' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'unique' => true,
              'email' => true,
              'length' => 128,
             ),
             'login' => 
             array(
              'type' => 'string',
              'notnull' => false,
              'unique' => true,
              'length' => 128,
             ),
             'password_hash' => 
             array(
              'type' => 'string',
              'length' => 32,
             ),
             'password_salt' => 
             array(
              'type' => 'string',
              'length' => 8,
             ),
             'role' => 
             array(
              'type' => 'enum',
              'notnull' => true,
              'values' => 
              array(
              0 => 'administrator',
              1 => 'member',
              2 => 'merchant',
              ),
              'length' => NULL,
             ),
             'password_reset_code' => 
             array(
              'type' => 'string',
              'length' => 8,
             ),
             'password_reset_code_created_at' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
             ),
             'activated' => 
             array(
              'type' => 'boolean',
              'length' => 25,
             ),
             'activation_code' => 
             array(
              'type' => 'string',
              'length' => 8,
             ),
             'registered' => 
             array(
              'type' => 'boolean',
              'length' => 25,
             ),
             'registration_ip' => 
             array(
              'type' => 'string',
              'ip' => true,
              'length' => 15,
             ),
             'fio' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'location' => 
             array(
              'type' => 'string',
              'length' => 2,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('users');
    }
}