<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addcatalogproducts extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('catalog_products', array(
             'id' => 
             array(
              'type' => 'integer',
              'unsigned' => true,
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'image_filename' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 45,
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => NULL,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('catalog_products');
    }
}