<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addmailer extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('mailer', array(
             'id' => 
             array(
              'type' => 'integer',
              'unsigned' => true,
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'email' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'email' => true,
              'length' => 128,
             ),
             'subject' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'from' => 
             array(
              'type' => 'string',
              'email' => true,
              'length' => 128,
             ),
             'body' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => NULL,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             ));
    }

    public function down()
    {
        $this->dropTable('mailer');
    }
}