<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version26 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('catalog_features_products', 'catalog_features_products_product_id_catalog_products_id', array(
             'name' => 'catalog_features_products_product_id_catalog_products_id',
             'local' => 'product_id',
             'foreign' => 'id',
             'foreignTable' => 'catalog_products',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('catalog_features_products', 'catalog_features_products_features_value_id_features_value_id', array(
             'name' => 'catalog_features_products_features_value_id_features_value_id',
             'local' => 'features_value_id',
             'foreign' => 'id',
             'foreignTable' => 'features_value',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('catalog_features_products', 'catalog_features_products_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
        $this->addIndex('catalog_features_products', 'catalog_features_products_features_value_id', array(
             'fields' => 
             array(
              0 => 'features_value_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('catalog_features_products', 'catalog_features_products_product_id_catalog_products_id');
        $this->dropForeignKey('catalog_features_products', 'catalog_features_products_features_value_id_features_value_id');
        $this->removeIndex('catalog_features_products', 'catalog_features_products_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
        $this->removeIndex('catalog_features_products', 'catalog_features_products_features_value_id', array(
             'fields' => 
             array(
              0 => 'features_value_id',
             ),
             ));
    }
}