<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version32 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('catalog_products', 'catalog_products_brand_id_catalog_brands_id', array(
             'name' => 'catalog_products_brand_id_catalog_brands_id',
             'local' => 'brand_id',
             'foreign' => 'id',
             'foreignTable' => 'catalog_brands',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('catalog_products', 'catalog_products_brand_id', array(
             'fields' => 
             array(
              0 => 'brand_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('catalog_products', 'catalog_products_brand_id_catalog_brands_id');
        $this->removeIndex('catalog_products', 'catalog_products_brand_id', array(
             'fields' => 
             array(
              0 => 'brand_id',
             ),
             ));
    }
}