<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version24 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('catalog_categories', 'catalog_categories_features_group_id_features_groups_id', array(
             'name' => 'catalog_categories_features_group_id_features_groups_id',
             'local' => 'features_group_id',
             'foreign' => 'id',
             'foreignTable' => 'features_groups',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('catalog_categories', 'catalog_categories_features_group_id', array(
             'fields' => 
             array(
              0 => 'features_group_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('catalog_categories', 'catalog_categories_features_group_id_features_groups_id');
        $this->removeIndex('catalog_categories', 'catalog_categories_features_group_id', array(
             'fields' => 
             array(
              0 => 'features_group_id',
             ),
             ));
    }
}