<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version36 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('catalog_products', 'avg_price', 'decimal', '14', array(
             'scale' => '2',
             ));
    }

    public function down()
    {
        $this->removeColumn('catalog_products', 'avg_price');
    }
}