<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version33 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('catalog_prices', 'available', 'enum', '', array(
             'notnull' => '1',
             'values' => 
             array(
              0 => 'available',
              1 => 'in_stock',
             ),
             'default' => 'available',
             ));
    }

    public function down()
    {
        $this->removeColumn('catalog_prices', 'available');
    }
}