<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version34 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('catalog_prices', 'filename', 'string', '45', array(
             'notnull' => '1',
             ));
        $this->addColumn('catalog_products', 'min_price', 'decimal', '14', array(
             'scale' => '2',
             ));
        $this->addColumn('catalog_products', 'max_price', 'decimal', '14', array(
             'scale' => '2',
             ));
    }

    public function down()
    {
        $this->removeColumn('catalog_prices', 'filename');
        $this->removeColumn('catalog_products', 'min_price');
        $this->removeColumn('catalog_products', 'max_price');
    }
}