<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version37 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('catalog_my_products_list', array(
             'id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'length' => '4',
             ),
             'product_id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'length' => '4',
             ),
             ), array(
             'type' => 'INNODB',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('catalog_my_products_list');
    }
}