<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version42 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('catalog_products_reviews', 'approve', 'boolean', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('catalog_products_reviews', 'approve');
    }
}