<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version41 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('catalog_products_reviews', 'catalog_products_reviews_product_id_catalog_products_id', array(
             'name' => 'catalog_products_reviews_product_id_catalog_products_id',
             'local' => 'product_id',
             'foreign' => 'id',
             'foreignTable' => 'catalog_products',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('catalog_products_reviews', 'catalog_products_reviews_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('catalog_products_reviews', 'catalog_products_reviews_product_id_catalog_products_id');
        $this->removeIndex('catalog_products_reviews', 'catalog_products_reviews_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
    }
}