<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version47 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('comments', 'comments_user_id_users_id', array(
             'name' => 'comments_user_id_users_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'users',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('shops_comments', 'shops_comments_user_id_users_id', array(
             'name' => 'shops_comments_user_id_users_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'users',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('shops_comments', 'shops_comments_entity_id_shops_id', array(
             'name' => 'shops_comments_entity_id_shops_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'shops',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('comments', 'comments_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('shops_comments', 'shops_comments_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('shops_comments', 'shops_comments_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('comments', 'comments_user_id_users_id');
        $this->dropForeignKey('shops_comments', 'shops_comments_user_id_users_id');
        $this->dropForeignKey('shops_comments', 'shops_comments_entity_id_shops_id');
        $this->removeIndex('comments', 'comments_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('shops_comments', 'shops_comments_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('shops_comments', 'shops_comments_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
    }
}