<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version60 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('advertisment_banners', 'status', 'enum', '', array(
             'notnull' => '1',
             'values' => 
             array(
              0 => 'available',
              1 => 'disable',
             ),
             'default' => 'disable',
             ));
        $this->addColumn('advertisment_banners', 'period', 'int', '4', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('advertisment_banners', 'status');
        $this->removeColumn('advertisment_banners', 'period');
    }
}