<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version58 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('advertisment_banners_images', 'advertisment_banners_images_banner_id_advertisment_banners_id', array(
             'name' => 'advertisment_banners_images_banner_id_advertisment_banners_id',
             'local' => 'banner_id',
             'foreign' => 'id',
             'foreignTable' => 'advertisment_banners',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('advertisment_banners_images', 'advertisment_banners_images_banner_id', array(
             'fields' => 
             array(
              0 => 'banner_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('advertisment_banners_images', 'advertisment_banners_images_banner_id_advertisment_banners_id');
        $this->removeIndex('advertisment_banners_images', 'advertisment_banners_images_banner_id', array(
             'fields' => 
             array(
              0 => 'banner_id',
             ),
             ));
    }
}