<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version45 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('catalog_products_reviews', 'created_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->addColumn('catalog_products_reviews', 'updated_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->addColumn('reviews_must_deleted', 'created_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->addColumn('reviews_must_deleted', 'updated_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('catalog_products_reviews', 'created_at');
        $this->removeColumn('catalog_products_reviews', 'updated_at');
        $this->removeColumn('reviews_must_deleted', 'created_at');
        $this->removeColumn('reviews_must_deleted', 'updated_at');
    }
}