<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version44 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('catalog_products_reviews', 'catalog_products_reviews_user_id_users_id', array(
             'name' => 'catalog_products_reviews_user_id_users_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'users',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('catalog_products_reviews', 'catalog_products_reviews_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('catalog_products_reviews', 'catalog_products_reviews_user_id_users_id');
        $this->removeIndex('catalog_products_reviews', 'catalog_products_reviews_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }
}