<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version43 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('catalog_products_reviews', 'user_id', 'integer', '4', array(
             'unsigned' => '1',
             ));
        $this->changeColumn('catalog_products_reviews', 'approve', 'boolean', '25', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('catalog_products_reviews', 'user_id');
    }
}