<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version50 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('shops_comments', 'deleted_at', 'timestamp', '25', array(
             'default' => '',
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('shops_comments', 'deleted_at');
    }
}