<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version49 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('shops_comments', 'status');
        $this->addColumn('shops_comments', 'mark', 'enum', '', array(
             'values' => 
             array(
              0 => 'good',
              1 => 'normal',
              2 => 'bad',
             ),
             ));
    }

    public function down()
    {
        $this->addColumn('shops_comments', 'status', 'enum', '', array(
             'values' => 
             array(
              0 => 'good',
              1 => 'normal',
              2 => 'bad',
             ),
             ));
        $this->removeColumn('shops_comments', 'mark');
    }
}