<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version57 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('advertisment_banners', array(
             'id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'type' => 
             array(
              'type' => 'enum',
              'notnull' => '1',
              'values' => 
              array(
              0 => 'top',
              1 => 'right',
              ),
              'length' => '',
             ),
             'background_color' => 
             array(
              'type' => 'string',
              'length' => '7',
             ),
             'background_image' => 
             array(
              'type' => 'string',
              'length' => '45',
             ),
             'show_on' => 
             array(
              'type' => 'enum',
              'notnull' => '1',
              'values' => 
              array(
              0 => 'anywhere',
              1 => 'on-main',
              2 => 'none',
              ),
              'default' => 'none',
              'length' => '',
             ),
             'rotation' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'last_renewal_date' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'untill_date' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'INNODB',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('advertisment_banners_images', array(
             'id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'banner_id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'length' => '4',
             ),
             'image_filename' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '45',
             ),
             ), array(
             'type' => 'INNODB',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('advertisment_banners');
        $this->dropTable('advertisment_banners_images');
    }
}