<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version64 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('catalog_categories', 'image_filename', 'string', '45', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('catalog_categories', 'image_filename');
    }
}