<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version63 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('pages_translation', 'pages_translation_id_pages_id', array(
             'name' => 'pages_translation_id_pages_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'pages',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('pages_translation', 'pages_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('pages_translation', 'pages_translation_id_pages_id');
        $this->removeIndex('pages_translation', 'pages_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}