<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version66 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('catalog_categories_accessories', 'catalog_categories_accessories_category_id_catalog_categories_id', array(
             'name' => 'catalog_categories_accessories_category_id_catalog_categories_id',
             'local' => 'category_id',
             'foreign' => 'id',
             'foreignTable' => 'catalog_categories',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('catalog_categories_accessories', 'ccci', array(
             'name' => 'ccci',
             'local' => 'category_accessory_id',
             'foreign' => 'id',
             'foreignTable' => 'catalog_categories',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('catalog_categories_accessories', 'catalog_categories_accessories_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->addIndex('catalog_categories_accessories', 'catalog_categories_accessories_category_accessory_id', array(
             'fields' => 
             array(
              0 => 'category_accessory_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('catalog_categories_accessories', 'catalog_categories_accessories_category_id_catalog_categories_id');
        $this->dropForeignKey('catalog_categories_accessories', 'ccci');
        $this->removeIndex('catalog_categories_accessories', 'catalog_categories_accessories_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->removeIndex('catalog_categories_accessories', 'catalog_categories_accessories_category_accessory_id', array(
             'fields' => 
             array(
              0 => 'category_accessory_id',
             ),
             ));
    }
}