<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version68 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('users', 'location');
        $this->addColumn('users', 'city', 'string', '100', array(
             ));
    }

    public function down()
    {
        $this->addColumn('users', 'location', 'string', '2', array(
             ));
        $this->removeColumn('users', 'city');
    }
}