<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version72 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('catalog_products', 'image_to_download', 'string', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('catalog_products', 'image_to_download');
    }
}