<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version71 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('catalog_products_reviews', 'approve', 'integer', '1', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {

    }
}