<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version73 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('catalog_prices', 'description', 'string', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('catalog_prices', 'description');
    }
}