<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version78 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('catalog_prices', 'in_price');
        $this->addColumn('catalog_prices', 'exist', 'boolean', '25', array(
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->addColumn('catalog_prices', 'in_price', 'boolean', '25', array(
             'default' => '1',
             ));
        $this->removeColumn('catalog_prices', 'exist');
    }
}