<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version74 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('shops', 'type', 'enum', '', array(
             'notnull' => '1',
             'values' => 
             array(
              0 => 'normal',
              1 => 'internet',
             ),
             'default' => 'normal',
             ));
    }

    public function down()
    {
        $this->removeColumn('shops', 'type');
    }
}