<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version79 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('shops', 'price_updated_at', 'timestamp', '', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('shops', 'price_updated_at');
    }
}