<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version80 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('shops', 'price_updated_at', 'timestamp', '25', array(
             'notnull' => '',
             ));
        $this->changeColumn('users', 'email', 'string', '128', array(
             'notnull' => '1',
             'unique' => '',
             'email' => '1',
             ));
        $conn = Doctrine_Manager::connection();
        $conn->exec('ALTER TABLE users DROP INDEX email');
    }

    public function down()
    {

    }
}