<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version83 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('shops_managers', 'shops_managers_shop_id_shops_id');
        $this->createForeignKey('shops', 'shops_chain_shop_id_shops_chain_id', array(
             'name' => 'shops_chain_shop_id_shops_chain_id',
             'local' => 'chain_shop_id',
             'foreign' => 'id',
             'foreignTable' => 'shops_chain',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('shops', 'shops_chain_shop_id', array(
             'fields' => 
             array(
              0 => 'chain_shop_id',
             ),
             ));
    }

    public function down()
    {
        $this->createForeignKey('shops_managers', 'shops_managers_shop_id_shops_id', array(
             'name' => 'shops_managers_shop_id_shops_id',
             'local' => 'shop_id',
             'foreign' => 'id',
             'foreignTable' => 'shops',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->dropForeignKey('shops', 'shops_chain_shop_id_shops_chain_id');
        $this->removeIndex('shops', 'shops_chain_shop_id', array(
             'fields' => 
             array(
              0 => 'chain_shop_id',
             ),
             ));
    }
}