<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version88 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('shops_chain', 'shops_chain_user_id_users_id', array(
             'name' => 'shops_chain_user_id_users_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'users',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('shops_chain', 'shops_chain_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('shops_chain', 'shops_chain_user_id_users_id');
        $this->removeIndex('shops_chain', 'shops_chain_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }
}