<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version89 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('shops', 'chain_name', 'string', '255', array(
             ));
    }

    public function postUp()
    {
        $conn = Doctrine_Manager::connection();

$query = <<<QUERY
UPDATE  `shops` SET  `chain_name` =  name WHERE  `chain_shop_id` IS NULL;
QUERY;
        $conn->exec($query);
    }

    public function down()
    {
        $this->removeColumn('shops', 'chain_name');
    }
}