<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version82 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('shops_chain', array(
             'id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'INNODB',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->addColumn('shops', 'chain_shop_id', 'integer', '4', array(
             'unsigned' => '1',
             ));
        $this->addColumn('shops', 'manager_id', 'integer', '4', array(
             'unsigned' => '1',
             ));
        $this->changeColumn('shops_managers', 'shop_id', 'integer', '4', array(
             'unsigned' => '1',
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->dropTable('shops_chain');
        $this->removeColumn('shops', 'chain_shop_id');
        $this->removeColumn('shops', 'manager_id');
    }
}