<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version90 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('shops', 'message_id', 'integer', '4', array(
             'unsigned' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('shops', 'message_id');
    }
}