<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version94 extends Doctrine_Migration_Base
{
    public function up()
    {
        $conn = Doctrine_Manager::connection();
        $query = "INSERT INTO `catalog_brands` (`name`, `description`) VALUES ('unknown', 'unknown brand');";
        $conn->exec($query);
        $id = $conn->lastInsertId();
        $query = "INSERT INTO `settings` (`key`, `value`, `description`, `type`) VALUES ('unknown_brand', $id, 'unknown brand', 'int');";
        $conn->exec($query);
    }

    public function down()
    {
        $conn = Doctrine_Manager::connection();
        $query = "DELETE FROM `settings` WHERE `settings`.`key` = 'unknown_brand';";
        $conn->exec($query);
    }
}