<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version93 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('settings', 'type', 'enum', '', array(
             'notnull' => '1',
             'values' => 
             array(
              0 => 'boolean',
              1 => 'int',
             ),
             'default' => 'boolean',
             ));
    }

    public function down()
    {

    }
}