<?php

/**
 * Users_Model_Base_UserBase
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $email
 * @property string $login
 * @property string $password_hash
 * @property string $password_salt
 * @property enum $role
 * @property string $password_reset_code
 * @property timestamp $password_reset_code_created_at
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Users_Model_Base_UserBase extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('users');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('email', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => false,
             'email' => true,
             'length' => '128',
             ));
        $this->hasColumn('login', 'string', 128, array(
             'type' => 'string',
             'notnull' => false,
             'unique' => true,
             'length' => '128',
             ));
        $this->hasColumn('password_hash', 'string', 32, array(
             'type' => 'string',
             'length' => '32',
             ));
        $this->hasColumn('password_salt', 'string', 8, array(
             'type' => 'string',
             'length' => '8',
             ));
        $this->hasColumn('role', 'enum', null, array(
             'type' => 'enum',
             'notnull' => true,
             'values' => 
             array(
              0 => 'administrator',
              1 => 'member',
              2 => 'merchant',
             ),
             ));
        $this->hasColumn('password_reset_code', 'string', 8, array(
             'type' => 'string',
             'length' => '8',
             ));
        $this->hasColumn('password_reset_code_created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => '25',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}