<form class="formOtziv formFeedback" id="<?php echo $this->element->getId();?>"
       action="<?php echo $this->element->getAction();?>"
       method="<?php echo $this->element->getMethod();?>">
    <?php if ($this->element->email):?>
    <div class="registerRows registerRows2">
        <div class="labelContenter">
            <label for="<?php echo $this->element->email->getName(); ?>">
                <?php echo $this->element->email->getLabel(); ?>
            </label>
        </div>
        <div class="inputTextWide">
            <?php echo $this->element->email;?>
        </div>
    </div>
    <?php endif;?>
    <div class="registerRows">
        <div class="labelContenter">
            <label for="<?php echo $this->element->message->getName(); ?>">
                <?php echo $this->element->message->getLabel(); ?>
            </label>
        </div>
        <div class="inputTextarea">
            <?php echo $this->element->message;?>
        </div>
    </div>
    <div class="registerRows">
            <?php echo $this->element->captcha; ?>
    </div>
    <div class="formSbutton">
        <?php echo $this->element->submit;?>
    </div>
</form>