#!/usr/bin/env php
<?php
/**
 * Doctrine CLI script
 */

require_once 'common.php';

require_once 'Zend/Application.php';

// Create application, bootstrap, and run
$application = new Zend_Application(
    APPLICATION_ENV,
    APPLICATION_PATH . '/configs/application.xml'
);

$application->getBootstrap()
    ->bootstrap();

$search = new Marketplace_Model_SearchService();
$search->updateIndex();