<p>
    <?php echo $this->translate('Здравствуйте!'); ?>
</p>
<p>
    <?php echo $this->translate('Вы запросили сброс пароля на сайте eprice.kz.'); ?>
</p>
<p>
    <?php echo $this->translate('Для подтверждения сброса пароля пройдите, пожалуйста по указанной ссылке:'); ?>
    <br />
    <a href="<?php $url = $this->serverUrl() . $this->url(array('module' => 'users', 'controller' => 'index',
                                         'action' => 'password-reset',
                                         'id' => $this->user->id,
                                         'code' => $this->user->password_reset_code),
                                   'default', true); echo $url;?>">
       <?php echo $url; ?>
    </a>
<p>
    <?php echo $this->translate('Если же вы не запрашивали сброс пароля на сайте, просто проигнорируйте это письмо – больше мы вас не побеспокоим.'); ?>
</p>
<p>
    <?php echo $this->translate('С уважением,'); ?>
    <br />
    <?php echo $this->translate('команда eprice.kz'); ?>
</p>