<h2>
    <?php echo $this->title; ?>
</h2>

<?php if (is_object($this->users) && $this->users->count()): ?>
    <table id="table_users_list">
        <thead>
            <tr>
                <th><?php echo $this->translate('Email'); ?></th>
                <th><?php echo $this->translate('Имя'); ?></th>
                <th><?php echo $this->translate('Зарегистрирован'); ?></th>
                <th><?php echo $this->translate('Действие'); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->users as $user) : ?>
                <tr>
                    <td>
                        <?php echo $user->email; ?>
                    </td>
                    <td>
                        <?php //echo $user->name; ?>
                    </td>
                    <td>
                        <?php echo $user->created_at; ?>
                    </td>
                    <td>
                        [<a href="<?php echo $this->url(array(
                            'module'=>'users',
                            'action'=>'edit',
                            'id'=>$user->id,
                        ), 'default', true); ?>"><?php echo $this->translate('Редактировать'); ?></a>]
                        [<a href="<?php echo $this->url(array(
                            'module'=>'users',
                            'action'=>'delete',
                            'id'=>$user->id,
                        ), 'default', true); ?>"><?php echo $this->translate('Удалить'); ?></a>]
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<br />

<div class="pager">
    <?php echo $this->pagination($this->paginator)->create_links(); ?>
</div>

<?php else: ?>
    <?php echo $this->translate('Пока еще нет пользователей.'); ?>
<?php endif; ?>
