<?php

/**
 * Shops_Model_ChainShop
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Shops_Model_ChainShop extends Shops_Model_Base_ChainShop
{

    /**
     * Return user resource id
     *
     * @return string
     */
    public function getResourceId()
    {
        if ($this->user_id == @Zend_Auth::getInstance()->getIdentity()->id)
        {
            return 'object:shops:chain-shop:my';
        } else {
            return 'object:shops:chain-shop:foreign';
        }
    }


}