<?php

/**
 * Shops_Model_Comment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Shops_Model_Comment extends Shops_Model_Base_Comment
{
    public function getCreatedAtFormated(){
        $date = new Zend_Date($this->created_at);
        return $date->toString('dd.MM.Y');
    }
}