<?php

/**
 * Shops_Model_Manager
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Shops_Model_Manager extends Shops_Model_Base_Manager implements Zend_Acl_Resource_Interface
{
    /**
     * Return user resource id
     *
     * @return string
     */
    public function getResourceId()
    {
        if ($this->Shop->user_id == @Zend_Auth::getInstance()->getIdentity()->id) {
            return 'object:shops:manager:my';
        } else {
            return 'object:shops:manager:foreign';
        }
    }
}