<?php $this->headScript()->appendFile('/javascripts/comments.js'); ?>
<h1><?php echo $this->title;?></h1>
<?php echo $this->tabMenu('shops-comments', $this->paginator->getTotalItemCount()); ?>

    <?php if (is_object($this->comments)): $count = $this->comments->count(); else: $count = 0; endif; ?>
    <?php if ($count > 0): ?>
        <?php echo $this->render('partial/item-admin.phtml'); ?>
        <?php echo $this->pagination($this->paginator)->create_links('admin'); ?>

    <?php else: ?>
        <?php echo $this->infoMessage($this->translate('Отзывы к продавцам пока отсутствуют.')); ?>
    <?php endif;?>
