<?php

/**
 * Marketplace_Model_CategoryProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Marketplace_Model_CategoryProduct extends Marketplace_Model_Base_CategoryProduct
{

}