<?php

/**
 * Marketplace_Model_Product
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Marketplace_Model_Product extends Marketplace_Model_Base_Product implements Zend_Acl_Resource_Interface
{
    public function getPriceFormated()
    {
        $currency = new Zend_Currency();
        $price = $this->_get('price');
        $currency->setFormat(array('precision' => 0, 'symbol' => ''));
        $price = $currency->toCurrency($price);
        return substr($price, 0, strlen($price) - 2);
    }

    public function getPrice()
    {
        return round($this->_get('price'));
    }

    public function getCreatedAtFormated(){
        $date = new Zend_Date($this->created_at);
        return $date->toString('dd.MM.Y');
    }

    /**
     * Return user resource id
     *
     * @return string
     */
    public function getResourceId()
    {
        if ($this->user_id == @Zend_Auth::getInstance()->getIdentity()->id) {
            return 'object:marketplace:product:my';
        } else {
            return 'object:marketplace:product:foreign';
        }
    }
}